target: Severity
target_metric: MSE
n_select: 2
turbo: true
train_size: 0.7
preprocess: true
imputation_type: simple
numeric_imputation: knn
iterative_imputation_iters: 5
low_variance_threshold: 0
normalize: true
normalize_method: zscore
data_split_shuffle: true
fold_strategy: kfold
fold: 5
fold_shuffle: true
fold_groups: Site
n_jobs: -1
use_gpu: false
random_seed: 100
log_experiment: true
log_plots: true
log_profile: true
log_data: true
profile: true
data_split_stratify: false
# data_split_stratify: 
#   - Site

run_distributed: false
n_iter: 2
n_estimators: 2
search_algorithm: random
distributed_search_algorithm: optuna
search_library: scikit-learn 
distributed_search_library: tune-sklearn
early_stopping: asha
early_stopping_max_iters: 10

prediction_interval: 0.05

model_description: Regression model for Botrytis disease modelling.
author: default user

ensemble_methods:
  - boosting
  - bagging
  - blending
  - stacking

meta_model: dt

categorical_features:
  - Site
  - pruning
  - year
ignore_features: 
  - Variety
  - Date
  - first_sev1
  - end_sev23
  - end_sev1
  - first_sev23
  - end_sev23
  - doy
  - doy.july1st
  - previous.season
  - season

anomaly_model: iforest
contamination_fraction: 0.05

clustering_model: kmeans
num_clusters: 7
clustering_ground_truth: Site

numeric_imputation_target: linear
numeric_imputation_exogenous: linear
fold_strategy_ts: sliding
fh: 100
seasonal_period: null
ignore_seasonality_test: true
sp_detection: auto
max_sp_to_consider: 4
remove_harmonics: false
harmonic_order_method: harmonic_max
num_sps_to_use: 1
coverage: 0.95
enforce_exogenous: false
target_metric_ts: SMAPE
scale_target: zscore
transform_target: box-cox

num_latents: 120
num_epochs: 3000
lr: 0.01

optimisation_sampler: tpse
load_optimiser: false
n_trials: 300

draws: 100
chains: 4
distribution: truncated_normal
n_trees: 3000
