name: gp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.9.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - adagio==0.2.4
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiohttp-cors==0.7.0
      - aiohttp-retry==2.8.3
      - aiorwlock==1.3.0
      - aiosignal==1.3.1
      - alembic==1.11.1
      - altair==5.0.1
      - amqp==5.1.1
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.11.1
      - anyio==3.7.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arviz==0.15.1
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - asyncssh==2.13.1
      - atpublic==3.1.2
      - attrs==23.1.0
      - autoviz==0.1.720
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - billiard==3.6.4.0
      - bleach==6.0.0
      - blessed==1.20.0
      - bokeh==2.4.3
      - boto3==1.26.151
      - botocore==1.29.151
      - cachetools==5.3.1
      - catboost==1.2
      - category-encoders==2.6.1
      - celery==5.2.7
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.2.0
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - cmake==3.26.3
      - colorama==0.4.6
      - colorcet==3.0.1
      - colorful==0.5.5
      - colorlog==6.7.0
      - colour==0.1.5
      - comm==0.1.3
      - configobj==5.0.8
      - cons==0.4.5
      - contourpy==1.0.7
      - cryptography==41.0.1
      - cycler==0.11.0
      - cython==0.29.35
      - daal==2023.1.1
      - daal4py==2023.1.1
      - dacite==1.8.1
      - dash==2.10.2
      - dash-auth==2.0.0
      - dash-bootstrap-components==1.4.1
      - dash-core-components==2.0.0
      - dash-cytoscape==0.3.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2023.5.1
      - databricks-cli==0.17.7
      - deap==1.3.3
      - debugpy==1.6.7
      - decorator==5.1.1
      - deepchecks==0.17.2
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - dictdiffer==0.9.0
      - dill==0.3.6
      - diskcache==5.6.1
      - distlib==0.3.6
      - distro==1.8.0
      - docker==6.1.3
      - dpath==2.1.6
      - dtreeviz==2.2.1
      - dulwich==0.21.5
      - dvc==2.58.2
      - dvc-data==0.51.0
      - dvc-http==2.30.2
      - dvc-objects==0.22.0
      - dvc-render==0.5.3
      - dvc-studio-client==0.10.0
      - dvc-task==0.2.1
      - emoji==2.5.0
      - entrypoints==0.4
      - etuples==0.3.9
      - evidently==0.3.2.1
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - explainerdashboard==0.4.2.2
      - fairlearn==0.7.0
      - fastapi==0.96.0
      - fastjsonschema==2.17.1
      - fastprogress==1.0.3
      - ffmpy==0.3.0
      - filelock==3.12.0
      - flask==2.2.5
      - flask-simplelogin==0.1.2
      - flask-wtf==1.1.1
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - fonttools==4.39.4
      - frozenlist==1.3.3
      - fs==2.4.16
      - fsspec==2023.5.0
      - fugue==0.8.4
      - fugue-sql-antlr==0.1.6
      - funcy==2.0
      - gevent==22.10.2
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-api-core==2.11.0
      - google-auth==2.19.1
      - googleapis-common-protos==1.59.0
      - gpustat==1.1
      - gpytorch==1.11
      - gradio==3.34.0
      - gradio-client==0.2.6
      - grandalf==0.8
      - greenlet==2.0.2
      - grpcio==1.51.3
      - gunicorn==20.1.0
      - h11==0.14.0
      - h5netcdf==1.2.0
      - h5py==3.8.0
      - holoviews==1.14.9
      - htmlmin==0.1.12
      - httpcore==0.17.2
      - httpx==0.24.1
      - huggingface-hub==0.15.1
      - hvplot==0.7.3
      - hydra-core==1.3.2
      - idna==3.4
      - imagehash==4.3.1
      - imageio==2.31.0
      - imbalanced-learn==0.10.1
      - importlib-metadata==5.2.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - interpret==0.4.2
      - interpret-core==0.4.2
      - ipykernel==6.23.1
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.5
      - iterative-telemetry==0.0.8
      - itsdangerous==2.1.2
      - jaxtyping==0.2.20
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpickle==3.0.1
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-dash==0.4.2
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==1.1.4
      - kaleido==0.2.1
      - kiwisolver==1.4.4
      - kmodes==0.12.2
      - kombu==5.3.0
      - lazy-loader==0.2
      - lightgbm==3.3.5
      - lime==0.2.0.1
      - linear-operator==0.5.0
      - linkify-it-py==2.0.2
      - lit==16.0.5.post0
      - llvmlite==0.40.0
      - locket==1.0.0
      - logical-unification==0.4.6
      - m2cgen==0.10.0
      - mako==1.2.4
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - minikanren==1.0.3
      - mistune==2.0.5
      - mlflow==1.30.1
      - mlxtend==0.22.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - multimethod==1.9.1
      - multipledispatch==0.6.0
      - multiprocess==0.70.14
      - nanotime==0.5.2
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nltk==3.8.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numba==0.57.0
      - numpy==1.23.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==11.525.112
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencensus==0.11.2
      - opencensus-context==0.1.3
      - optuna==3.2.0
      - orjson==3.9.0
      - oyaml==1.0
      - packaging==21.3
      - pandas==1.5.3
      - pandas-dq==1.28
      - pandas-profiling==3.6.6
      - pandocfilters==1.5.0
      - panel==0.14.4
      - param==1.13.0
      - parso==0.8.3
      - partd==1.4.0
      - pathspec==0.11.1
      - patsy==0.5.3
      - pexpect==4.8.0
      - phik==0.12.3
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - plotly==5.14.1
      - plotly-resampler==0.8.3.2
      - pluggy==1.0.0
      - pmdarima==2.0.3
      - prometheus-client==0.17.0
      - prometheus-flask-exporter==0.22.4
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.5
      - psycopg2-binary==2.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-spy==0.3.14
      - pyamg==5.0.0
      - pyarrow==11.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycaret==3.0.0
      - pycparser==2.21
      - pyct==0.5.0
      - pydantic==1.10.8
      - pydot==1.4.2
      - pydub==0.25.1
      - pygit2==1.12.1
      - pygments==2.15.1
      - pygtrie==2.5.0
      - pyjwt==2.7.0
      - pymc==5.4.1
      - pynndescent==0.5.10
      - pynomaly==0.3.3
      - pyod==1.0.9
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pytensor==2.12.1
      - pytest==7.3.2
      - python-dateutil==2.8.2
      - python-graphviz==0.20.1
      - python-multipart==0.0.6
      - python-utils==3.6.0
      - pytz==2022.7.1
      - pyviz-comms==2.3.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==23.2.1
      - qpd==0.4.3
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - querystring-parser==1.2.4
      - ray==2.4.0
      - regex==2023.6.3
      - requests==2.31.0
      - retrying==1.3.4
      - rich==13.4.1
      - rsa==4.9
      - ruamel-yaml==0.17.31
      - ruamel-yaml-clib==0.2.7
      - s3transfer==0.6.1
      - salib==1.4.7
      - schemdraw==0.15
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scikit-learn-intelex==2023.1.1
      - scikit-plot==0.3.7
      - scipy==1.10.1
      - scmrepo==1.0.3
      - seaborn==0.12.2
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - shap==0.41.0
      - shortuuid==1.0.11
      - shtab==1.6.1
      - six==1.16.0
      - skope-rules==1.0.1
      - sktime==0.17.0
      - slicer==0.0.7
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlalchemy==1.4.48
      - sqlglot==15.2.0
      - sqlparse==0.4.4
      - sqltrie==0.3.1
      - stack-data==0.6.2
      - starlette==0.27.0
      - statsforecast==1.5.0
      - statsmodels==0.14.0
      - stopit==1.1.2
      - sympy==1.12
      - tabulate==0.9.0
      - tangled-up-in-unicode==0.2.0
      - tbats==1.1.3
      - tbb==2021.9.0
      - tenacity==8.2.2
      - tensorboardx==2.6
      - terminado==0.17.1
      - textblob==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.11.8
      - toolz==0.12.0
      - torch==2.0.1
      - tornado==6.3.2
      - tpot==0.12.0
      - tqdm==4.65.0
      - trace-updater==0.0.9.1
      - traitlets==5.9.0
      - treeinterpreter==0.2.3
      - triad==0.9.0
      - triton==2.0.0
      - tune-sklearn==0.4.5
      - typeguard==2.13.3
      - typing-extensions==4.6.3
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - umap-learn==0.5.3
      - update-checker==0.18.0
      - urllib3==1.26.16
      - uvicorn==0.22.0
      - vine==5.0.0
      - virtualenv==20.21.0
      - visions==0.7.5
      - voluptuous==0.13.1
      - waitress==2.1.2
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - websockets==11.0.3
      - werkzeug==2.2.3
      - widgetsnbextension==3.6.4
      - wordcloud==1.9.2
      - wrapt==1.15.0
      - wtforms==3.0.1
      - wurlitzer==3.0.3
      - xarray==2023.5.0
      - xarray-einstats==0.5.1
      - xgboost==1.7.5
      - xlrd==2.0.1
      - xxhash==3.2.0
      - yarl==1.9.2
      - ydata-profiling==4.2.0
      - yellowbrick==1.5
      - zc-lockfile==3.0.post1
      - zipp==3.15.0
      - zope-event==4.6
      - zope-interface==6.0
