name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.11.3
  - atk-1.0=2.38.0
  - bcrypt=3.2.2
  - blinker=1.6.2
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - configparser=5.3.0
  - cryptography=41.0.3
  - databricks-cli=0.17.7
  - docker-py=6.1.3
  - entrypoints=0.4
  - expat=2.5.0
  - flask=2.3.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.32
  - gorilla=0.4.0
  - graphite2=1.3.13
  - graphviz=8.1.0
  - greenlet=2.0.2
  - gtk2=2.24.33
  - gts=0.7.6
  - gunicorn=21.2.0
  - harfbuzz=7.3.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_resources=6.0.1
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - jsonpatch=1.32
  - jsonpointer=2.0
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgd=2.3.3
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=4.23.4
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libuuid=2.38.1
  - libwebp=1.3.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - mako=1.2.4
  - markupsafe=2.1.3
  - ncurses=6.4
  - numpy=1.25.2
  - oauthlib=3.2.2
  - openssl=3.1.2
  - packaging=23.1
  - pandas=2.0.3
  - pango=1.50.14
  - paramiko=3.3.1
  - pcre2=10.40
  - pixman=0.40.0
  - pluggy=1.2.0
  - protobuf=4.23.4
  - pthread-stubs=0.4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyjwt=2.8.0
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-graphviz=0.16
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - querystring_parser=1.2.4
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.0.0
  - simplejson=3.19.1
  - six=1.16.0
  - smmap=3.0.5
  - sqlalchemy=2.0.20
  - sqlite=3.42.0
  - sqlparse=0.4.4
  - tabulate=0.9.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.66.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - websocket-client=1.6.1
  - werkzeug=2.3.7
  - wheel=0.41.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.16.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - asttokens==2.0.5
      - backcall==0.2.0
      - certifi==2022.6.15
      - chardet==5.1.0
      - conda==4.11.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.5.1
      - decorator==5.1.1
      - ebooklib==0.18
      - elementpath==4.1.2
      - et-xmlfile==1.1.0
      - executing==0.8.3
      - fonttools==4.40.0
      - ipykernel==6.9.2
      - ipython==8.1.1
      - jedi==0.18.1
      - joblib==1.2.0
      - jupyter-client==7.1.2
      - jupyter-core==4.9.2
      - kiwisolver==1.4.4
      - load-dotenv==0.1.0
      - lxml==4.9.2
      - markdown==3.4.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.3
      - mlflow==2.4.1
      - nest-asyncio==1.5.4
      - openpyxl==3.1.2
      - parso==0.8.3
      - pdfminer-six==20221105
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==23.3.1
      - plotly==5.14.1
      - ply==3.11
      - prompt-toolkit==3.0.28
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.1
      - pydub==0.25.1
      - pygments==2.11.2
      - pyparsing==3.1.0
      - pyperclip==1.8.2
      - pyqt6==6.5.1
      - pyqt6-qt6==6.5.1
      - pyqt6-sip==13.5.1
      - pyside2==5.15.2.1
      - python-dotenv==1.0.0
      - python-vlc==3.0.18122
      - pyzmq==22.3.0
      - qualcoder==3.4
      - rispy==0.7.1
      - scikit-learn==1.2.2
      - scipy==1.11.0
      - shiboken2==5.15.2.1
      - speechrecognition==3.10.0
      - stack-data==0.2.0
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - tornado==6.1
      - traitlets==5.1.1
      - urllib3==1.26.16
      - wcwidth==0.2.5
      - xmlschema==2.3.0
