channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=23.0.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - importlib-metadata==6.7.0
  - jinja2==3.1.2
  - matplotlib==3.7.1
  - numpy==1.23.5
  - packaging==23.1
  - pandas==1.5.3
  - pycaret==3.0.3
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
